[package]
name = "example-templates"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
askama = "0.11"
graphul = { path = "../../." }
tokio = { version = "1.0", features = ["full"] }
